#!/bin/sh

. /etc/profile

err() {
	export TERM="linux"

	clear
	setterm -cursor off

	tput ${UNLOCKER_TPUT:-setaf 1}
	echo "${UNLOCKER_ERRMSG:-"err: can't boot"}"
	tput sgr0

	while true; do sleep 1; done
}

for i in ${UNLOCKER_BOOTARGS:-boot}; do
	grep -wq "$i" /proc/cmdline || err
done

ROOT_PART="$(df | grep -E '/$' | awk '{ print $1 }')"

DEVICE_UUID="$(cat /sys/class/dmi/id/product_uuid)"
PART_UUID="$(blkid | grep "$ROOT_PART" | awk '{print $2 }' | sed -e 's/UUID="//g' -e 's/"//g')"

case $1 in
	"--help")
		cat <<EOF
Usage: $0 [option]
    --help
        Shows this lovely help message
    --print
        Prints the device password
    --encrypt
        Attempts to encrypt \$UNLOCKER

    anything else
        Attempts to unlock \$UNLOCKER
EOF
		;;
	"--print")
		echo "$DEVICE_UUID$PART_UUID"
		;;
	"--encrypt")
		echo Use Password: $($0 --print)
		fscrypt encrypt "$(eval echo ~$UNLOCKER)"
		;;
	*)
		$0 --print | fscrypt unlock "$(eval echo ~$UNLOCKER)" || err
		;;
esac
