#!/bin/sh

. /etc/profile

err() {
	export TERM="linux"

	clear
	setterm -cursor off

	tput ${UNLOCKER_TPUT:-setaf 1}
	echo "${UNLOCKER_ERRMSG:-"err: can't boot"}"
	tput sgr0

	while true; do sleep 1; done
}

for i in ${UNLOCKER_BOOTARGS:-boot}; do
	grep -wq "$i" /proc/cmdline || err
done

ROOT_PART="$(df | grep -E '/$' | awk '{ print $1 }')"
ROOT_DISK="$(lsblk -o MOUNTPOINT,PKNAME | grep -E '^/ ' | awk '{ print $2 }')"

UNLOCKER_PASS="${UNLOCKER_PASS:-%deviceid-%diskid-%partid-%bname-%bios-%vendor}"

BOARD_NAME="$(cat /sys/class/dmi/id/board_name)"
BIOS_VENDOR="$(cat /sys/class/dmi/id/bios_vendor)"
BOARD_VENDOR="$(cat /sys/class/dmi/id/board_vendor)"
DEVICE_UUID="$(cat /sys/class/dmi/id/product_uuid)"
DISK_UUID="$(fdisk -l /dev/$ROOT_DISK | grep 'Disk identifier' | awk '{ print $3 }')"
PART_UUID="$(blkid -o export $ROOT_PART | grep -E "^UUID" | sed -e 's/UUID=//g' -e 's/"//g')"

case $1 in
	"--help")
		cat <<EOF
Usage: $0 [option]
    --help
        Shows this lovely help message
    --print
        Prints the device password
    --encrypt
        Attempts to encrypt \$UNLOCKER

    anything else
        Attempts to unlock \$UNLOCKER
EOF
		;;
	"--print")
		echo "$UNLOCKER_PASS" | \
			sed "s/\%deviceid/$DEVICE_UUID/g" | \
			sed "s/\%vendor/$BOARD_VENDOR/g" | \
			sed "s/\%unlocker/$UNLOCKER/g" | \
			sed "s/\%diskid/$DISK_UUID/g" | \
			sed "s/\%bios/$BIOS_VENDOR/g" | \
			sed "s/\%bname/$BOARD_NAME/g" | \
			sed "s/\%partid/$PART_UUID/g"
		;;
	"--encrypt")
		echo Use Password: $($0 --print)
		fscrypt encrypt "$(eval echo ~$UNLOCKER)"
		;;
	*)
		$0 --print | fscrypt unlock "$(eval echo ~$UNLOCKER)" || err
		;;
esac
