#!/bin/sh

. /etc/profile

err() {
	echo "${UNLOCKER_ERRMSG:-err: can't boot}"
	while true; do sleep 1; done
}; grep -wq "boot" /proc/cmdline || err

ROOT_PART="$(df | grep -E '/$' | awk '{ print $1 }')"

DEVICE_UUID="$(cat /sys/class/dmi/id/product_uuid)"
PART_UUID="$(blkid | grep "$ROOT_PART" | awk '{print $2 }' | sed -e 's/UUID="//g' -e 's/"//g')"

case $1 in
	"--help")
		cat <<EOF
Usage: $0 [option]
    --help
        Shows this lovely help message
    --print
        Prints the device password
    --encrypt
        Attempts to encrypt \$UNLOCKER

    anything else
        Attempts to unlock \$UNLOCKER
EOF
		;;
	"--print")
		echo "$DEVICE_UUID$PART_UUID"
		;;
	"--encrypt")
		echo Use Password: $($0 --print)
		fscrypt encrypt "$(eval echo ~$UNLOCKER)"
		;;
	*)
		$0 --print | fscrypt unlock "$(eval echo ~$UNLOCKER)" || err
		;;
esac
